# docker-compose.yml

services:
  db:
    image: postgres:latest
    container_name: pg-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: labdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d labdb"]
      interval: 2s
      timeout: 2s
      retries: 20

  client:
    build: .
    container_name: pg-client
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: labdb
      DB_USER: user
      DB_PASS: pass
    depends_on:
      db:
        condition: service_healthy
